# Generated by Django 2.2.8 on 2021-05-26 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0014_auto_20210525_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferalCoupen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupen_code', models.CharField(blank=True, max_length=12)),
                ('discount', models.IntegerField(default=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
