# Generated by Django 2.2.8 on 2021-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0015_referalcoupen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleCoupen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupen_title', models.CharField(max_length=30)),
                ('coupen_code', models.CharField(max_length=30)),
                ('coupen_offer', models.FloatField()),
                ('validity', models.BooleanField(default=True)),
            ],
        ),
    ]
