# Generated by Django 2.2.8 on 2021-05-28 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0016_simplecoupen'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.SimpleCoupen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
