# Generated by Django 2.2.8 on 2021-05-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210512_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='user_cancel',
            field=models.CharField(default=False, max_length=20, null=True),
        ),
    ]
