# Generated by Django 2.2.8 on 2021-05-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(default='pending', max_length=20, null=True),
        ),
    ]
