# Generated by Django 2.2.8 on 2021-05-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(default='Pending', max_length=20, null=True),
        ),
    ]
